### PR TITLE
docs:  linux installation guide improvements

### PR DESCRIPTION
**Pull request by onuralpszr**
* Package requirements  added for both ubuntu and fedora.
* Linux installation require compilation  so I wrote how to do for easier for others. (I had to check issues and project to find it so I wanted make it easier for others as well)

### CODE REVIEW

**Comment by onuralpszr** [comment]
First of all thank you for great work. I like to offer some improvements here is the first one :) 

Thank you.
cc @gespona

**Comment by onuralpszr** [comment]
@gespona  friendly ping*

**Comment by gespona** [comment]
@onuralpszr Sorry for late reply here ! somehow I missed your messages 😓     I'd really appreciate your contribution, in fact we had some issues in the past with Linux, so really appreciate your collaboration. Did you faced any issue running in Linux inside editor or with binaries? it's something I will test again soon

**Comment by onuralpszr** [comment]
Hello, I had some problems and overcome and first I had  was switching scenes, I upgrade depthai-core version and It worked better, but before sending as a PR I wanted to make sure it is properly compiled so I wrote docs for installation, I am using "Fedora 37" on my tests, and right I was able to play pretty nicely after I upgrade depthai-core but 1 scene I don't remember the name but It start crash, It was probably because of depthai-core version update I made so I can understand, I look for that solution and I did some changes but not finished yet.


Overall, It was compiled and working fine in VFX mode and I was able to do changes in desktop and such It was fun to play with it. I did not tried on mobile, but I think there is a way to do that I just did not look yet. 

That is my first impressions from last month :)

**Comment by sliwowitz** [comment]
@onuralpszr please also check my review comment - the `ffmpeg` is not needed anymore since the latest version uses a `gif` file for loader animation.

**Comment by onuralpszr** [comment]
@sliwowitz I did not see your review yet (reminder)

**Comment by onuralpszr** [comment]
I see that this has been added into docs thank you @gespona

**Pull request closed without merging**
